import math

def ishappy(number):
	unhappy=(4, 16, 37, 58, 89, 145, 42, 20)
	myNumber=number
	addup=0
	while True:
		digit=int(math.log10(myNumber))+1
		addup=0
		for i in range(digit):
			addup+=pow((myNumber%pow(10,i+1)-myNumber%pow(10,i))/(pow(10,i)),2)
		if addup==1:
			return 1
		for i in unhappy:
			if i==addup:
				return 0
		myNumber=addup
	return 0

Limit=128
f=open("Python's Happy numbers.txt","w")
f.write("List of happy numbers from 1 to "+str(Limit)+" generated by Python\n")
for i in range(1,Limit+1):
	if ishappy(i)==1:
		f.write(str(i)+'\n')
f.close()