clear all
close all
clc

Limit=3e4;
unhappy=[4, 16, 37, 58, 89, 145, 42, 20];
FID=fopen("Octave's Happy numbers.txt","w");
fprintf(FID,"List of happy numbers from 1 to %i generated by Octave\n",Limit)
for ThisNumber=1:1:Limit
    number=ThisNumber;
    addup=0;
    check=0;
    while(check==0)
        digits=fix(log10(number))+1;
        addup=0;
        for i=1:digits
            addup+=((mod(number,10^i)-mod(number,10^(i-1)))/(10^(i-1)))^2;
        endfor
        if (addup==1)
            fprintf(FID,"%i\n",ThisNumber);
            break
        endif
        for i=1:1:length(unhappy)
            if addup==unhappy(i)
                check=1;
                break
            endif
        endfor
        number=addup;
    endwhile
endfor
fclose(FID);